// Copyright 2020 Hajime Hoshi
// SPDX-License-Identifier: Apache-2.0

// +build ignore

package main

import (
	"flag"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

var flagTar = flag.String("tar", "", "tar file of Go binary")

func main() {
	flag.Parse()
	if *flagTar == "" {
		// TODO: This works only on macOS and Linux. Take care about other platforms.
		fmt.Fprintf(os.Stderr, "-tar must be specified. Download from https://dl.google.com/go/go%s.%s-%s.tar.gz and use it.\n", goversion, runtime.GOOS, runtime.GOARCH)
		os.Exit(1)
	}

	if err := run(); err != nil {
		panic(err)
	}
}

func run() error {
	tmp, err := ioutil.TempDir("", "playground-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	if err := prepareGo(tmp); err != nil {
		return err
	}
	if err := genStdfiles(tmp); err != nil {
		return err
	}
	if err := genBins(tmp); err != nil {
		return err
	}
	return nil
}

const (
	goversion = "1.14beta1"
)

func prepareGo(tmp string) error {
	const gotarfile = "go.tar.gz"

	fmt.Printf("Copying %s\n", gotarfile)
	
	in, err := os.Open(*flagTar)
	if err != nil {
		return err
	}
	defer in.Close()

	gotar := filepath.Join(tmp, gotarfile)
	f, err := os.Create(gotar)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := io.Copy(f, in); err != nil {
		return err
	}

	fmt.Printf("Extracting %s\n", gotarfile)

	cmd := exec.Command("tar", "-xzf", gotarfile)
	cmd.Stderr = os.Stderr
	cmd.Dir = tmp
	if err := cmd.Run(); err != nil {
		return err
	}

	gobin := filepath.Join(tmp, "go", "bin", "go")
	cmd = exec.Command(gobin, "version")
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return err
	}
	fmt.Printf("Checking go version: %s\n", strings.TrimSpace(string(out)))

	return nil
}

func stdfiles(tmp string) (string, []string, error) {
	gobin := filepath.Join(tmp, "go", "bin", "go")

	var src string
	{
		cmd := exec.Command(gobin, "list", "-f", "{{.Dir}}", "runtime")
		cmd.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm")
		cmd.Stderr = os.Stderr
		out, err := cmd.Output()
		if err != nil {
			return "", nil, err
		}
		src = filepath.Join(strings.TrimSpace(string(out)), "..")
	}

	cmd := exec.Command(gobin, "list", "-f", "dir: {{.Dir}}\n{{range .GoFiles}}file: {{.}}\n{{end}}{{range .SFiles}}file: {{.}}\n{{end}}", "std")
	cmd.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm")
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return "", nil, err
	}

	var files []string
	var dir string
	for _, line := range strings.Split(string(out), "\n") {
		const predir = "dir:"
		const prefile = "file:"
		if strings.HasPrefix(line, predir) {
			dir = strings.TrimSpace(line[len(predir):])
			continue
		}
		if strings.HasPrefix(line, prefile) {
			file := strings.TrimSpace(line[len(prefile):])
			rel, err := filepath.Rel(src, filepath.Join(dir, file))
			if err != nil {
				return "", nil, err
			}
			files = append(files, rel)
		}
	}
	return src, files, nil
}

func genStdfiles(tmp string) error {
	fmt.Printf("Generating stdfiles.js\n")

	src, fs, err := stdfiles(tmp)
	if err != nil {
		return err
	}

	contents := map[string]string{}
	for _, f := range fs {
		c, err := ioutil.ReadFile(filepath.Join(src, f))
		if err != nil {
			return err
		}
		contents[f] = base64.StdEncoding.EncodeToString(c)
	}

	f, err := os.Create("stdfiles.js")
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "// Copyright 2020 Hajime Hoshi")
	fmt.Fprintln(f, "// SPDX-License-Identifier: Apache-2.0")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by gen.go. DO NOT EDIT.")
	fmt.Fprintln(f)

	fmt.Fprint(f, "export const stdfiles = ")
	e := json.NewEncoder(f)
	if err := e.Encode(contents); err != nil {
		return err
	}
	return nil
}

func genBins(tmp string) error {
	gobin := filepath.Join(tmp, "go", "bin", "go")

	files := []struct {
		Name string
		Path string
	}{
		{
			Name: "go" + goversion + ".wasm",
			Path: "cmd/go",
		},
		{
			Name: "compile" + goversion + ".wasm",
			Path: "cmd/compile",
		},
		{
			Name: "link" + goversion + ".wasm",
			Path: "cmd/link",
		},
	}
	for _, file := range files {
		fmt.Printf("Generating %s\n", file.Name)
		cmd := exec.Command(gobin, "build", "-trimpath", "-o=bin/"+file.Name, file.Path)
		cmd.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm")
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			return err
		}
	}
	return nil
}
